'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Plus,RotateCcw,Search,Volume2,Upload,Check,Archive,Clock,ArrowUpRight,WifiOff,Download,FileText,X,Layers,PenLine,History,RefreshCw,CheckCircle2,ChevronDown,ChevronUp} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Skeleton} from '@/components/ui/skeleton';
import {toast} from 'sonner';
import {Toaster} from '@/components/ui/sonner';
import {type Word,type Candidate,type Review,keyFor,normal,schedule} from '@/lib/types';
import {EnrichmentQueue} from '@/lib/enrichment-queue';
import {readApiResponse} from '@/lib/http-response';

async function api(path:string,method='GET',data?:unknown,signal?:AbortSignal){const response=await fetch(path,{signal,method,credentials:'same-origin',cache:'no-store',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const value:any=await readApiResponse(response);return value}
async function allWords(){let cursor:string|null=null;const words:Word[]=[];let serverNow=Date.now();do{const page=await api('/api/words'+(cursor?'?cursor='+encodeURIComponent(cursor):''));words.push(...page.words);cursor=page.nextCursor;serverNow=page.serverNow}while(cursor);return {words:Array.from(new Map(words.map(w=>[w.id,w])).values()),serverNow}}
const sample='Small, consistent efforts compound over time. Learning a word in context makes it easier to recall when you need it.';
const labels:Record<string,string>={again:'再練一次',hard:'有點難',good:'記得',easy:'很熟悉'};
const uid=()=>crypto.randomUUID();
const newest=(old:Word|undefined,next:Word)=>old&&old.revision>next.revision?old:old&&old.revision===next.revision&&old.term===next.term&&old.lookupStatus==='found'&&next.lookupStatus!=='found'?{...next,dictionary:old.dictionary,phonetic:old.phonetic,lookupStatus:old.lookupStatus}:next;
const stamp=(n:number)=>new Date(n).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function dueLabel(n:number){const diff=n-Date.now();if(diff<=0)return '現在可複習';if(diff<3600000)return `${Math.ceil(diff/60000)} 分鐘後`;if(diff<86400000)return `${Math.ceil(diff/3600000)} 小時後`;return new Date(n).toLocaleDateString('zh-TW',{month:'short',day:'numeric'})}
function meaning(w:Word){return w.definition||w.dictionary[0]?.definition||''}

export default function VocabularyApp({userKey}:{userKey:string}){
 const [clockTick,setClockTick]=useState(Date.now()),[serverOffset,setServerOffset]=useState(0);
 const [tab,setTab]=useState('capture'),[words,setWords]=useState<Word[]>([]),[history,setHistory]=useState<Review[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(true);
 const [source,setSource]=useState(''),[draftReady,setDraftReady]=useState(false),[analyzed,setAnalyzed]=useState(''),[candidates,setCandidates]=useState<Candidate[]>([]),[paragraph,setParagraph]=useState(false),[phrase,setPhrase]=useState(''),[phraseContext,setPhraseContext]=useState(''),[drag,setDrag]=useState(false);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[editor,setEditor]=useState<Word|null>(null),[expanded,setExpanded]=useState<Record<string,boolean>>({}),[enriching,setEnriching]=useState(false);
 const [queue,setQueue]=useState<Word[]>([]),[reviewIndex,setReviewIndex]=useState(0),[revealed,setRevealed]=useState(false),[sessionCount,setSessionCount]=useState(0),[reviewBusy,setReviewBusy]=useState(false),[reviewError,setReviewError]=useState('');
 const [installPrompt,setInstallPrompt]=useState<any>(null);
 const [persistenceError,setPersistenceError]=useState('');
 const enrichmentRef=useRef<EnrichmentQueue|null>(null);
 const reportPersistenceError=useCallback((message:string)=>{queueMicrotask(()=>setPersistenceError(message))},[]);
 const fileRef=useRef<HTMLInputElement>(null),sourceRef=useRef<HTMLTextAreaElement>(null),paragraphRef=useRef<HTMLDivElement>(null),saveLock=useRef(false),reviewLock=useRef(false),eventRef=useRef<{wordId:string;rating:string;key:string}|null>(null),refreshSeq=useRef(0);
 function navigate(value:string){if(!saveLock.current&&!reviewLock.current)setTab(value)}
 const active=useMemo(()=>words.filter(w=>w.archivedAt===null),[words]);
 const due=useMemo(()=>active.filter(w=>w.dueAt<=clockTick+serverOffset).sort((a,b)=>a.dueAt-b.dueAt),[active,clockTick,serverOffset]);
 const selected=candidates.filter(c=>c.selected),current=queue[reviewIndex],existingKeys=useMemo(()=>new Set(words.map(keyFor)),[words]);
 const latest=active.slice(0,4),todayCount=history.filter(r=>new Date(r.reviewedAt).toLocaleDateString()===new Date().toLocaleDateString()).length;
 const refresh=useCallback(async()=>{const seq=++refreshSeq.current;try{setError('');const [w,h]=await Promise.all([allWords(),api('/api/reviews')]);if(seq!==refreshSeq.current)return;setWords(prev=>{const incoming=new Set(w.words.map((x:Word)=>x.id));return [...w.words.map((next:Word)=>newest(prev.find(old=>old.id===next.id),next)),...prev.filter(old=>!incoming.has(old.id))]});setHistory(h.reviews);setServerOffset(w.serverNow-Date.now());setClockTick(Date.now());return w.words as Word[]}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{
  let attempts:unknown={},nextRequestAt:unknown=0;try{const saved=JSON.parse(localStorage.getItem(`vocab-lookups:${userKey}`)||'{}');if(saved&&typeof saved==='object'){attempts=saved.version===1?saved.attempts:saved;nextRequestAt=saved.nextRequestAt}}catch{reportPersistenceError('瀏覽器無法保留本機進度；已儲存的詞彙仍在雲端。請勿關閉尚未確認的草稿。')}
  const queue=new EnrichmentQueue({attempts,nextRequestAt,lookup:id=>api('/api/lookup','POST',{id},AbortSignal.timeout(15000)),onWord:word=>setWords(prev=>prev.map(w=>w.id===word.id?newest(w,word):w)),onBusy:setEnriching,onFailure:message=>toast(message),persist:(attempts,nextRequestAt)=>{try{localStorage.setItem(`vocab-lookups:${userKey}`,JSON.stringify({version:1,attempts,nextRequestAt}))}catch{reportPersistenceError('瀏覽器無法保留本機進度；已儲存的詞彙仍在雲端。請勿關閉尚未確認的草稿。')}}});
  enrichmentRef.current=queue;queue.setOnline(navigator.onLine);return()=>{queue.dispose();enrichmentRef.current=null};
 },[userKey,reportPersistenceError]);
 useEffect(()=>{if(!loading&&!error)enrichmentRef.current?.sync(words)},[words,loading,error]);
 useEffect(()=>{void refresh();setOnline(navigator.onLine);const update=()=>{const connected=navigator.onLine;setOnline(connected);enrichmentRef.current?.setOnline(connected);if(connected)void refresh()};window.addEventListener('online',update);window.addEventListener('offline',update);const install=(e:Event)=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',install);if('serviceWorker'in navigator&&location.hostname!=='localhost'&&location.hostname!=='127.0.0.1')navigator.serviceWorker.register('/sw.js').catch(()=>{});try{const savedTab=localStorage.getItem(`vocab-tab:${userKey}`);if(savedTab&&['capture','review','library','history'].includes(savedTab))setTab(savedTab);const stored=localStorage.getItem(`vocab-draft:${userKey}`);if(stored){try{const d=JSON.parse(stored);if(typeof d.source==='string')setSource(d.source);if(typeof d.analyzed==='string')setAnalyzed(d.analyzed);setParagraph(!!d.paragraph);if(Array.isArray(d.candidates))setCandidates(d.candidates.filter((c:any)=>c&&typeof c.id==='string'&&typeof c.term==='string'&&typeof c.context==='string'&&typeof c.sense==='string').slice(0,100))}catch{setSource(stored)}}}catch{reportPersistenceError('瀏覽器無法讀取本機草稿；已儲存的詞彙仍在雲端。')}setDraftReady(true);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('beforeinstallprompt',install)}},[refresh,userKey,reportPersistenceError]);
 useEffect(()=>{const tick=()=>setClockTick(Date.now());const timer=setInterval(tick,30000);const visible=()=>{tick();if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',visible);window.addEventListener('focus',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('focus',visible)}},[refresh]);
 useEffect(()=>{if(draftReady)try{localStorage.setItem(`vocab-draft:${userKey}`,JSON.stringify({source,analyzed,paragraph,candidates}));localStorage.setItem(`vocab-tab:${userKey}`,tab)}catch{reportPersistenceError('瀏覽器無法保留本機進度；已儲存的詞彙仍在雲端。請勿關閉尚未確認的草稿。')}},[source,analyzed,paragraph,candidates,tab,draftReady,userKey,reportPersistenceError]);
 const updateWord=(word:Word)=>{setWords(prev=>prev.map(w=>w.id===word.id?newest(w,word):w))};
 function speak(text:string){if(!('speechSynthesis'in window)){toast.error('這個瀏覽器暫不支援朗讀');return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=0.85;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)utterance.voice=voice;utterance.onerror=()=>toast.error('語音無法播放，請確認裝置的英文語音可用');speechSynthesis.speak(utterance)}
 function analyze(text=source,force?:'list'|'paragraph'){
  if(saveLock.current)return;
  if(!text.trim()){toast.error('先貼上一個詞、一份清單或一段英文');sourceRef.current?.focus();return}
  if(text.length>20000){toast.error('請將內容縮短至 20,000 字元以內');return}
  const lines=text.trim().split(/\n+/).map(s=>s.trim()).filter(Boolean);const isList=force==='list'||(force!=='paragraph'&&(lines.length>1&&lines.every(l=>l.split(/\s+/).length<=8&&!/[.!?]$/.test(l))||!/[.!?]/.test(text)&&text.split(/\s+/).length<=8));
  setAnalyzed(text.trim());setParagraph(!isList);setPhrase('');setExpanded({});
  if(isList){const parts=lines.flatMap(line=>line.split(/[,;\t]+/)).map(s=>s.replace(/^\s*[-•\d.)]+\s+/,'').trim()).filter(Boolean);if(parts.length>100){toast.error('一次最多 100 個詞，請分批貼上');return}const unique=Array.from(new Set(parts.map(normal)));const next=unique.map(term=>({id:uid(),term:parts.find(p=>normal(p)===term)||term,context:'',sense:'',selected:true}));setCandidates(next)}else setCandidates([]);
 }
 function addCandidate(term:string,context:string){term=term.trim().replace(/^[“”"'.,!?;:()]+|[“”"'.,!?;:()]+$/g,'');if(!term||term.length>100)return;if(candidates.length>=100){toast.error('每批最多 100 個詞');return}const c={id:uid(),term,context,sense:'',selected:true};if(candidates.some(w=>keyFor(w)===keyFor(c))){toast('這個詞已在待存清單');return}setCandidates(prev=>[...prev,c]);setPhrase('')}
 function selectedPhrase(){const selection=window.getSelection();if(!selection?.rangeCount||!paragraphRef.current?.contains(selection.anchorNode)||!paragraphRef.current?.contains(selection.focusNode))return;const text=selection.toString().trim();if(text&&text.length<=100){let node=selection.anchorNode?.parentElement;const sentence=node?.closest('[data-sentence]')?.textContent||analyzed;setPhrase(text);setPhraseContext(sentence.slice(0,1500))}}
 async function readFile(file?:File){if(!file||saveLock.current)return;if(!file.name.toLowerCase().endsWith('.txt')){toast.error('目前支援 .txt 文字檔；OCR 與 PDF 將來再加入');return}if(file.size>80000){toast.error('檔案太大，請使用 80 KB 以下的 TXT');return}const text=await file.text();if(saveLock.current)return;if(text.length>20000){toast.error('請分成每次 20,000 字元以內');return}setSource(text);setAnalyzed('');setCandidates([]);toast.success('文字已載入，確認後再選擇詞彙')}
 function enrich(ids:string[]){enrichmentRef.current?.retry(ids)}
 async function saveCandidates(){if(saveLock.current||reviewLock.current||!selected.length)return;saveLock.current=true;setBusy(true);try{const result=await api('/api/words','POST',{words:selected.map(({term,context,sense})=>({term,context,sense}))});setWords(prev=>[...result.words,...prev]);toast.success(`已儲存 ${result.added} 個詞${result.duplicates?` · ${result.duplicates} 筆相同內容已跳過`:''}`);const submittedIds=new Set(selected.map(c=>c.id));setCandidates(prev=>prev.filter(c=>!submittedIds.has(c.id)));if(result.words.length){setSessionCount(result.words.length);setQueue(result.words.slice(0,10));setReviewIndex(0);setRevealed(false);}if(selected.length===candidates.length){setSource('');setAnalyzed('')}await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false);saveLock.current=false}}
 function startReview(items=due){if(!items.length||reviewLock.current||saveLock.current)return;setQueue(items.slice(0,10));setReviewIndex(0);setSessionCount(Math.min(items.length,10));setRevealed(false);setReviewError('');eventRef.current=null;navigate('review')}
 async function rateWord(rating:string){if(!current||!revealed||reviewLock.current||saveLock.current)return;reviewLock.current=true;setReviewBusy(true);setReviewError('');if(eventRef.current&&eventRef.current.wordId===current.id&&eventRef.current.rating!==rating){setReviewError('上一次評分可能已送出，請先重試同一個評分');reviewLock.current=false;setReviewBusy(false);return}if(!eventRef.current||eventRef.current.wordId!==current.id)eventRef.current={wordId:current.id,rating,key:uid()};try{const r=await api('/api/reviews','POST',{wordId:current.id,revision:current.revision,eventKey:eventRef.current.key,rating,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'});if(r.word)updateWord(r.word);setReviewIndex(i=>i+1);setRevealed(false);eventRef.current=null;void refresh()}catch(e){setReviewError((e as Error).message)}finally{setReviewBusy(false);reviewLock.current=false}}
 useEffect(()=>{if(tab!=='review'||!current||editor)return;const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,button,[role="dialog"]'))return;if(e.code==='Space'){e.preventDefault();setRevealed(true)}if(revealed&&['1','2','3','4'].includes(e.key)){e.preventDefault();void rateWord(['again','hard','good','easy'][Number(e.key)-1])}if(e.key==='Escape'){navigate('capture')}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[tab,current,revealed,editor]);
 async function saveEdit(){if(!editor||saveLock.current)return;saveLock.current=true;setBusy(true);try{const r=await api('/api/words','PATCH',editor);updateWord(r.word);setEditor(null);toast.success('已更新')}catch(e){toast.error((e as Error).message)}finally{setBusy(false);saveLock.current=false}}
 async function archiveWord(w:Word){if(saveLock.current)return;saveLock.current=true;try{const r=await api('/api/words','PATCH',{id:w.id,revision:w.revision,archived:w.archivedAt===null});updateWord(r.word);toast.success(w.archivedAt===null?'已封存，可在封存頁還原':'已還原')}catch(e){toast.error((e as Error).message)}finally{saveLock.current=false}}
 function exportData(){const payload={exportedAt:new Date().toISOString(),words,recentReviews:history};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`vocabulary-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);toast('已匯出全部詞彙與最近 300 筆複習紀錄')}
 useEffect(()=>{const model=(document as any).modelContext;if(!model?.registerTool)return;const ctrl=new AbortController();Promise.resolve(model.registerTool({name:'stage_vocabulary_text',title:'Stage vocabulary text',description:'Fill the capture box and analyze pasted English text. Does not save words or reviews.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:20000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){if(saveLock.current||reviewLock.current)throw new Error('A save is in progress; try staging again after it completes');const value=input as {text?:unknown};if(typeof value?.text!=='string'||!value.text.trim()||value.text.length>20000)throw new Error('Text must contain 1–20000 characters');setSource(value.text);analyze(value.text);navigate('capture');return {staged:true,saved:false}}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort()},[]);
 const visible=words.filter(w=>(filter==='archived'?w.archivedAt!==null:w.archivedAt===null)&&(filter!=='due'||w.dueAt<=Date.now())&&normal(`${w.term} ${w.context} ${w.sense} ${w.definition} ${w.dictionary.map(m=>m.definition).join(' ')}`).includes(normal(query)));
 const sentences=analyzed.match(/[^.!?\n]+(?:[.!?]+["']?|$)|[^\n]+/g)||[analyzed];

 return <div className="app-shell"><Toaster position="bottom-right" richColors closeButton/><header className="topbar"><a className="brand" href="/" aria-label="English Vocabulary 首頁"><span className="brand-icon">v<span>.</span></span><span>English<span className="brand-light">vocabulary</span></span></a><div className="top-actions"><form action="/auth/signout" method="post"><button className="text-button" type="submit" disabled={busy||reviewBusy}>登出</button></form><span className="private-label"><span className="tiny-lock">●</span> 私人詞彙本</span>{installPrompt&&<button className="quiet-button" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null)}}><Download size={16}/>安裝</button>}<button className="icon-button" aria-label="重新載入資料" onClick={()=>void refresh()}><RefreshCw size={18}/></button></div></header>
 <main><div className="page-heading"><div><div className="eyebrow">YOUR WORDS, IN CONTEXT</div><h1>讓遇見的詞，變成會用的詞</h1></div><div className="mini-stats"><div><strong aria-label={loading||error?'載入中':undefined}>{loading||error?'—':active.length}</strong><span>已收集</span></div><div><strong>{loading||error?'—':due.length}</strong><span>待複習</span></div><div><strong>{loading||error?'—':todayCount}</strong><span>今天練習</span></div></div></div>
 {persistenceError&&<div className="notice warning" role="status"><span>{persistenceError}</span></div>}
 {!online&&<div className="notice warning"><WifiOff size={18}/><span>目前離線。草稿保留在這台裝置；儲存與複習需要網路。</span></div>}
 {error&&<div className="notice error" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>重試</button></div>}
 <Tabs value={tab} onValueChange={value=>{if(!reviewLock.current)navigate(value)}} className="main-tabs"><TabsList className="navigation" aria-label="主要功能"><TabsTrigger value="capture"><Plus size={18}/>收集 <span>Collect</span></TabsTrigger><TabsTrigger value="review"><RotateCcw size={18}/>複習 <span>Review</span>{due.length>0&&<b className="count-pill">{due.length}</b>}</TabsTrigger><TabsTrigger value="library"><BookOpen size={18}/>詞彙本 <span>Library</span></TabsTrigger><TabsTrigger value="history"><History size={18}/>紀錄 <span>History</span></TabsTrigger></TabsList>
 <TabsContent value="capture"><div className="capture-grid"><section className="panel capture-panel"><fieldset disabled={busy} className="capture-fieldset"><div className="section-title"><div><h2>先收下，不用整理</h2><p>貼上單字、清單或一段英文，再選你想記住的。</p></div><span className="step-label">01 / COLLECT</span></div>
 <div className={`paste-area ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void readFile(e.dataTransfer.files[0])}}><textarea ref={sourceRef} aria-label="貼上英文單字、清單或段落" value={source} onChange={e=>setSource(e.target.value)} placeholder={'resilient\n\n或貼上一段英文，把值得記住的詞留在原句裡。'} maxLength={20000} spellCheck={false}/><div className="paste-bottom"><button className="text-button" onClick={()=>fileRef.current?.click()}><Upload size={16}/>拖入或選擇 TXT</button><span>{source.length.toLocaleString()} / 20,000</span><input ref={fileRef} type="file" accept=".txt,text/plain" hidden onChange={e=>{void readFile(e.target.files?.[0]);e.target.value=''}}/></div></div>
 <div className="capture-actions"><button className="text-button" onClick={()=>{setSource(sample);analyze(sample,'paragraph')}}>試一段例句</button><button className="primary-button" onClick={()=>analyze()} disabled={!source.trim()}>選擇詞彙 <Layers size={17}/></button></div>
 <p className="microcopy">草稿僅儲存在這台裝置 · 確認後才會存入私人雲端詞彙本</p>
 {analyzed&&<div className="selection-section"><div className="section-title compact"><h3>{paragraph?'點選單字，或反白選取片語':'確認這一批詞彙'}</h3><button className="text-button" onClick={()=>analyze(analyzed,paragraph?'list':'paragraph')}>{paragraph?'改為清單':'改為段落'}</button></div>
 {paragraph&&<><div className="paragraph-text" ref={paragraphRef} onMouseUp={selectedPhrase} onTouchEnd={selectedPhrase}>{sentences.map((sentence,si)=><span data-sentence key={si}>{sentence.split(/([A-Za-z]+(?:['’\-][A-Za-z]+)*)/g).map((part,pi)=>/^[A-Za-z]/.test(part)?<button className={candidates.some(c=>normal(c.term)===normal(part)&&c.context===sentence.trim())?'word-token picked':'word-token'} key={pi} onClick={()=>{if(!window.getSelection()?.toString().trim())addCandidate(part,sentence.trim())}}>{part}</button>:<span key={pi}>{part}</span>)}{' '}</span>)}</div>{phrase&&<div className="phrase-bar"><span>“{phrase}”</span><button className="small-button" onClick={()=>{addCandidate(phrase,phraseContext);window.getSelection()?.removeAllRanges()}}>加入片語</button><button aria-label="取消選擇片語" className="icon-button" onClick={()=>setPhrase('')}><X size={15}/></button></div>}</>}
 {candidates.length>0?<><div className="candidate-toolbar"><label><Checkbox checked={selected.length===candidates.length} onCheckedChange={v=>setCandidates(prev=>prev.map(c=>({...c,selected:!!v})))} aria-label="全選待存詞彙"/>已選 {selected.length} / {candidates.length}</label><span>同詞不同原句或詞義會分開儲存</span></div><div className="candidate-list">{candidates.map(c=>{const exact=existingKeys.has(keyFor(c));const similar=words.filter(w=>normal(w.term)===normal(c.term)).length;return <div className="candidate" key={c.id}><div className="candidate-main"><Checkbox checked={c.selected} onCheckedChange={v=>setCandidates(prev=>prev.map(x=>x.id===c.id?{...x,selected:!!v}:x))} aria-label={`選擇 ${c.term}`}/><input aria-label={`詞彙 ${c.term}`} value={c.term} maxLength={100} onChange={e=>setCandidates(prev=>prev.map(x=>x.id===c.id?{...x,term:e.target.value}:x))}/>{exact?<span className="duplicate-note">{words.find(w=>keyFor(w)===keyFor(c))?.archivedAt!==null?'已存在（已封存）':'相同內容已存在'}</span>:similar>0?<span className="duplicate-note new-sense">已有 {similar} 個語境</span>:null}<button className="icon-button" aria-label={`編輯 ${c.term} 的語境與詞義`} onClick={()=>setExpanded(prev=>({...prev,[c.id]:!prev[c.id]}))}>{expanded[c.id]?<ChevronUp size={17}/>:<PenLine size={16}/>}</button><button className="icon-button" aria-label={`移除待存 ${c.term}`} onClick={()=>setCandidates(prev=>prev.filter(x=>x.id!==c.id))}><X size={16}/></button></div>{c.context&&!expanded[c.id]&&<p className="candidate-context">{c.context}</p>}{expanded[c.id]&&<div className="candidate-fields"><label>原句（可留空）<textarea maxLength={1500} value={c.context} onChange={e=>setCandidates(prev=>prev.map(x=>x.id===c.id?{...x,context:e.target.value}:x))}/></label><label>這次的詞義標記（可留空）<input placeholder="例如：bank 的「河岸」義" maxLength={100} value={c.sense} onChange={e=>setCandidates(prev=>prev.map(x=>x.id===c.id?{...x,sense:e.target.value}:x))}/></label></div>}</div>})}</div><div className="confirm-row"><button className="quiet-button" onClick={()=>{setCandidates([]);setAnalyzed('')}} disabled={busy}>取消這批</button><button className="primary-button" disabled={!selected.length||busy||!online||loading||!!error} onClick={()=>void saveCandidates()}><Check size={18}/>{busy?'儲存中…':`確認儲存 ${selected.length} 個詞`}</button></div></>:<p className="empty-selection">選詞後會出現在這裡；整段英文不會自動全部加入。</p>}
 </div>}
 </fieldset></section><aside className="side-stack"><section className="review-invite"><div className="eyebrow">A LITTLE, EVERY DAY</div><div className="review-number">{loading||error?'—':due.length}<span>{loading?'正在讀取詞彙':'個詞等你複習'}</span></div><p>不必一次記住。花兩分鐘，讓印象更深一點。</p><button className="dark-button" onClick={()=>startReview()} disabled={!due.length||loading||!online}>開始一小輪 <span>最多 10 個</span></button><div className="review-note"><Clock size={15}/>依你的記憶情況安排下一次</div></section>
 {queue.length>0&&tab==='capture'&&<section className="saved-invite"><CheckCircle2 size={22}/><div><h3>詞彙已收好</h3><p>現在練一次，會更容易記住。</p><button className="text-button" onClick={()=>startReview(queue)}>馬上練習這批</button></div></section>}
 <section className="panel recent-panel"><div className="section-title compact"><h3>最近遇見</h3><button className="text-button" onClick={()=>navigate('library')}>全部</button></div>{loading?<Skeleton className="h-32 w-full"/>:latest.length?latest.map(w=><button className="recent-word" key={w.id} onClick={()=>setEditor({...w})}><span><strong>{w.term}</strong><small>{w.context||meaning(w)||'等待補充釋義'}</small></span><span className="recent-date">{new Date(w.createdAt).toLocaleDateString('zh-TW',{month:'numeric',day:'numeric'})}</span></button>):<div className="quiet-empty"><BookOpen size={28}/><p>從第一個詞開始<br/><span>不需要標籤，也沒有必填分類。</span></p></div>}</section><p className="dictionary-note"><BookOpen size={15}/>自動釋義來自 Free Dictionary API，僅提供英文；未查到的詞也能儲存。</p>{enriching&&<p className="enriching"><RefreshCw size={14} className="spin"/>詞彙已儲存，正在補充英文釋義…</p>}</aside></div></TabsContent>
 <TabsContent value="review"><section className="review-surface"><div className="section-title"><div><div className="eyebrow">SPACED PRACTICE</div><h2>先回想，再翻開</h2></div>{current&&<button className="quiet-button" disabled={reviewBusy} onClick={()=>{setQueue([]);setSessionCount(0);setReviewError('')}}>結束這一輪</button>}</div>
 {loading?<div className="quiet-empty" role="status">正在載入你的詞彙…</div>:current?<><div className="review-progress"><span>{reviewIndex+1} / {queue.length}</span><Progress value={reviewIndex/queue.length*100}/></div><div className="flashcard"><div className="card-topline"><span>{current.sense||'想想它在原句裡的意思'}</span><button className="icon-button" aria-label={`朗讀 ${current.term}`} onClick={()=>speak(current.term)}><Volume2 size={23}/></button></div><h2 className="review-term">{current.term}</h2>{current.context&&<p className="review-context">{current.context}</p>}{revealed?<div className="answer"><span className="eyebrow">MEANING</span><p>{meaning(words.find(w=>w.id===current.id)||current)||'目前沒有釋義。可以先憑原句回想，或到詞彙本補上自己的說明。'}</p>{(words.find(w=>w.id===current.id)||current).phonetic&&<span className="phonetic">{(words.find(w=>w.id===current.id)||current).phonetic}</span>}</div>:<button className="reveal-button" onClick={()=>setRevealed(true)}>顯示釋義 <kbd>Space</kbd></button>}</div>{reviewError&&<div className="notice error" role="alert"><span>{reviewError}</span><button onClick={()=>{void refresh();setQueue([]);setSessionCount(0);eventRef.current=null}}>重新載入這一輪</button></div>}{revealed?<div className="ratings">{(['again','hard','good','easy'] as const).map((rating,i)=><button key={rating} className={`rating rating-${rating}`} disabled={reviewBusy||!online||!!eventRef.current&&eventRef.current.rating!==rating} onClick={()=>void rateWord(rating)}><span><kbd>{i+1}</kbd>{labels[rating]}</span><small>{dueLabel(schedule(rating,current.intervalDays,current.streak,Date.now()).dueAt)}</small></button>)}</div>:<p className="review-hint">在心裡說出意思，或用它造一句話。</p>}<p className="microcopy center">每次評分儲存到雲端 · 排程依經過時間計算，日期依裝置時區顯示</p></>:<div className="session-empty"><div className="large-symbol">{sessionCount?<CheckCircle2 size={42}/>:<RotateCcw size={42}/>}</div><h3>{sessionCount?'這一輪完成了':'一小輪，就夠了'}</h3><p>{sessionCount?`已練習 ${reviewIndex} 個詞。下一次複習時間已安排好。`:due.length?`${due.length} 個詞可以複習，先練最多 10 個。`:'目前沒有到期的詞。先收集一些，或自由練習現有詞彙。'}</p><div className="center-actions">{due.length>0&&<button className="primary-button" onClick={()=>startReview()} disabled={!online}>開始複習</button>}{active.length>0&&<button className="quiet-button" onClick={()=>startReview([...active].sort(()=>Math.random()-.5))} disabled={!online}>自由練習</button>}<button className="quiet-button" onClick={()=>navigate('capture')}>去收集詞彙</button></div></div>}
 </section></TabsContent>
 <TabsContent value="library"><section className="panel library-panel"><div className="section-title"><div><h2>你的詞彙，連著原句</h2><p>同一個詞可以保留多個語境；釋義與詞義隨時能改。</p></div><button className="quiet-button" onClick={exportData} disabled={!words.length}><Download size={17}/>匯出</button></div><div className="library-toolbar"><label className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋詞彙、原句或釋義" aria-label="搜尋詞彙"/></label><div className="filter-buttons" role="group" aria-label="詞彙篩選">{[['all','全部'],['due','待複習'],['archived','已封存']].map(([value,label])=><button className={filter===value?'active':''} key={value} onClick={()=>setFilter(value)} aria-pressed={filter===value}>{label}</button>)}</div></div><div className="library-count">{loading||error?'正在讀取詞彙…':`${visible.length} 筆詞彙`} {filter==='archived'&&'· 封存詞彙不進入複習，可以隨時還原'}</div>{loading?<Skeleton className="h-40 w-full"/>:visible.length?<div className="word-grid">{visible.map(w=><article className="word-card" key={w.id}><div className="word-card-title"><button className="word-title" onClick={()=>setEditor({...w})}>{w.term}</button><button className="icon-button" aria-label={`朗讀 ${w.term}`} onClick={()=>speak(w.term)}><Volume2 size={18}/></button></div>{w.phonetic&&<div className="phonetic">{w.phonetic}</div>}{w.sense&&<span className="sense-tag">{w.sense}</span>}<p className={`definition ${!meaning(w)?'muted':''}`}>{meaning(w)||({pending:'釋義待查詢',unavailable:'詞典暫時無法連線，可重試',not_found:'詞典未找到，點編輯補充意思'}[w.lookupStatus]||'暫無釋義')}</p>{w.context&&<p className="word-context">{w.context}</p>}<div className="word-card-footer"><span className={w.dueAt<=Date.now()?'due-tag':'due-later'}>{w.archivedAt!==null?'已封存':dueLabel(w.dueAt)}</span><div>{!meaning(w)&&<button className="icon-button" aria-label={`查詢 ${w.term} 釋義`} disabled={enriching||!online} onClick={()=>void enrich([w.id])}><RefreshCw size={15}/></button>}<button className="icon-button" aria-label={`編輯 ${w.term}`} onClick={()=>setEditor({...w})}><PenLine size={16}/></button><button className="icon-button" aria-label={w.archivedAt===null?`封存 ${w.term}`:`還原 ${w.term}`} disabled={!online} onClick={()=>void archiveWord(w)}>{w.archivedAt===null?<Archive size={16}/>:<RotateCcw size={16}/>}</button></div></div></article>)}</div>:<div className="session-empty smaller"><Search size={34}/><h3>{query?'沒有符合的詞彙':'這裡還沒有詞彙'}</h3><p>{query?'試試其他詞，或清除篩選。':'遇到一個值得記住的詞，就把它收進來。'}</p>{!query&&<button className="primary-button" onClick={()=>navigate('capture')}>新增詞彙</button>}</div>}</section></TabsContent>
 <TabsContent value="history"><section className="panel history-panel"><div className="section-title"><div><h2>每一次想起來，都算數</h2><p>最近 300 筆複習紀錄 · 時間顯示為你的裝置時區</p></div><span className="step-label">PRACTICE LOG</span></div>{loading?<Skeleton className="h-32 w-full"/>:history.length?<div className="history-list">{history.map(r=><div className="history-row" key={r.id}><span className={`history-dot ${r.rating}`}/><strong>{r.term}</strong><span className="history-rating">{labels[r.rating]}</span><time>{stamp(r.reviewedAt)}</time><span className="history-next">下次 {stamp(r.dueAfter)}</span></div>)}</div>:<div className="quiet-empty"><History size={36}/><p>還沒有複習紀錄<br/><span>完成第一張卡片後，就會出現在這裡。</span></p></div>}</section></TabsContent>
 </Tabs><footer className="footer"><span>English vocabulary · 一次收集，慢慢記住</span><span>雲端儲存 · 離線時僅保留本機草稿</span></footer></main>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null)}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>編輯詞彙</DialogTitle><DialogDescription>保留你需要的意思。不同原句或詞義可以各自複習。</DialogDescription></DialogHeader>{editor&&<form onSubmit={e=>{e.preventDefault();void saveEdit()}}><fieldset disabled={busy} className="editor-fieldset"><label>單字或片語<input autoFocus required maxLength={100} value={editor.term} onChange={e=>setEditor({...editor,term:e.target.value})}/></label><label>原句<textarea rows={3} maxLength={1500} value={editor.context} onChange={e=>setEditor({...editor,context:e.target.value})}/></label><label>詞義標記 <span>可留空</span><input maxLength={100} placeholder="例如：河岸" value={editor.sense} onChange={e=>setEditor({...editor,sense:e.target.value})}/></label><label>自己的釋義 <span>可用中文或英文</span><textarea rows={3} maxLength={2000} value={editor.definition} placeholder={editor.dictionary[0]?.definition||'寫下你要記住的意思'} onChange={e=>setEditor({...editor,definition:e.target.value})}/></label>{editor.dictionary.length>0&&<details className="dictionary-details"><summary>檢視英文詞典釋義（{editor.dictionary.length}）</summary>{editor.dictionary.map((m,i)=><div key={i}><b>{m.partOfSpeech}</b><p>{m.definition}</p>{m.example&&<small>{m.example}</small>}<button type="button" className="text-button" onClick={()=>setEditor({...editor,definition:m.definition,sense:editor.sense||m.partOfSpeech})}>採用這個釋義</button></div>)}<a href="https://dictionaryapi.dev/" target="_blank" rel="noreferrer">Free Dictionary API</a></details>}<div className="dialog-actions"><button className="quiet-button" type="button" disabled={busy} onClick={()=>setEditor(null)}>取消</button><button className="primary-button" disabled={busy||!online} type="submit">{busy?'儲存中…':'儲存修改'}</button></div></fieldset></form>}</DialogContent></Dialog>
 </div>
}
